services:

  fanficdownloader:
    build: .
    container_name: fanficdownloader

    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - ASPNETCORE_URLS=http://+:8080
      - FLARESOLVERR__URL=http://flaresolverr:8191

    ports:
      - "8080:8080"

    depends_on:
      - flaresolverr

    restart: unless-stopped


  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr

    ports:
      - "8191:8191"

    restart: unless-stopped
    