services:

  fanficdownloader:
    build: .
    container_name: fanficdownloader

    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - ASPNETCORE_URLS=http://+:8080
      - FLARESOLVERR__URL=http://flaresolverr:8191

    ports:
      - "8080:8080"
    volumes:
      - ./FanficDownloader.Web/appsettings.json:/app/appsettings.json

    depends_on:
      - flaresolverr
      - postgres

    restart: unless-stopped


  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    restart: unless-stopped
    shm_size: "512mb"


  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: fanficdownloader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
    postgres_data: